meta_product_name: "SurfBuddy"
meta_title: "SurfBuddy - The surfing conditions helper you need"
meta_description: "The best platform to find the best surfspot for your level"
meta_image: "cover-surfbuddy.jpg" # should exist in `app/assets/images/`
